#!/bin/bash

echo 'git push....'
git checkout master
git push
git checkout production
git merge master
git push
git checkout master

echo 're-run build...'
npm run build
echo 'Start depoly build to ali cloud /srv/www/react_app'
scp -r ./build/* root@47.74.183.6:/srv/www/react_app

